### ISSUE TITLE
Connection reset with ChatInputInteractionEvent after 6 min inactivity

### ISSUE THREAD

**Issue by twonirwana** [Discord4J/Discord4J#1020]
**To Reproduce:**
Using a simple ChatInputInteractionEvent handling, starting the bot and wait for a minimum of 6 min and using the slash command

```
 @Override
 public Publisher<?> onChatInputInteraction(@NonNull ChatInputInteractionEvent event) {
            return event.reply(InteractionApplicationCommandCallbackSpec.builder()
                    .content("test")
                    .build());
    }
```

**Expected Behavior:** reply with "test"

**Actual Behavior:** 
```
23:17:42.452 [reactor-http-nio-3] DEBUG d.gateway.DefaultGatewayClient - [G:11f06b26, S:0] Heartbeat acknowledged after PT0.1132651S
23:17:50.805 [d4j-events-1] DEBUG discord4j.rest.request.RequestStream - [B:db1ee72c] RequestStream completed
23:17:50.806 [d4j-events-1] DEBUG discord4j.rest.request.RequestStream - [B:98d12163] RequestStream completed
23:17:50.806 [d4j-events-1] DEBUG discord4j.rest.request.RequestStream - [B:a39dc574] RequestStream completed
23:17:50.807 [d4j-events-1] DEBUG discord4j.rest.request.RequestStream - [B:98d12163, R:1c4f9b53, G:11f06b26, S:0] POST /interactions/894332444621283418/aW50ZXJhY3Rpb246ODk0MzMyNDQ0NjIxMjgzNDE4OlppTks4a3NyUkp0WFNSWTdmbjJRQkczOU9yeEwyaVFZZmluMGZZUXdzOEV1Q0JhS090OE5UME05aGQ2eXNGeFRFS0ptbXBQNms1R09HZ3JzeXlqUktEWVBESHlrdnBSUk5YUkFGclJhTFYzUE0xajZBY2dQc2pLZVd4MUwyUFcx/callback
23:17:50.834 [reactor-http-nio-2] WARN  r.n.http.client.HttpClientConnect - [id:d0b4c5ab-5, L:/192.168.10.52:56353 - R:discord.com/162.159.138.232:443] The connection observed an error
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:345)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:376)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
23:17:50.848 [reactor-http-nio-2] DEBUG discord4j.rest.request.RequestStream - [B:98d12163] Ready to consume next request after onError
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:345)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ? Request to POST /interactions/894332444621283418/aW50ZXJhY3Rpb246ODk0MzMyNDQ0NjIxMjgzNDE4OlppTks4a3NyUkp0WFNSWTdmbjJRQkczOU9yeEwyaVFZZmluMGZZUXdzOEV1Q0JhS090OE5UME05aGQ2eXNGeFRFS0ptbXBQNms1R09HZ3JzeXlqUktEWVBESHlrdnBSUk5YUkFGclJhTFYzUE0xajZBY2dQc2pLZVd4MUwyUFcx/callback [RequestStream]
	|_ checkpoint ? Request to POST /interactions/894332444621283418/aW50ZXJhY3Rpb246ODk0MzMyNDQ0NjIxMjgzNDE4OlppTks4a3NyUkp0WFNSWTdmbjJRQkczOU9yeEwyaVFZZmluMGZZUXdzOEV1Q0JhS090OE5UME05aGQ2eXNGeFRFS0ptbXBQNms1R09HZ3JzeXlqUktEWVBESHlrdnBSUk5YUkFGclJhTFYzUE0xajZBY2dQc2pLZVd4MUwyUFcx/callback [DefaultRouter]
Stack trace:
		at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:345)
		at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:376)
		at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
		at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
		at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:832)
23:18:23.599 [d4j-parallel-1-5] DEBUG d.gateway.DefaultGatewayClient - [G:11f06b26, S:0] Sending heartbeat PT41.1457889S after last ACK
23:18:23.751 [reactor-http-nio-3] DEBUG d.gateway.DefaultGatewayClient - [G:11f06b26, S:0] Heartbeat acknowledged after PT0.1532834S
```

**Version:** 3.2

**Other:** The problem only surface if there are 6 min with no interaction. The second slash command, immediately after the first works without problem.

**Comment by NovaFox161** [comment]
`Connection reset` is beyond D4J's control. Its likely you might have an unstable internet connection or some other networking issue that is causing the instability.
I'm unable to reproduce this within our `example-projects` or my own bots.

You're welcome to join the Discord4J server and ask for further. I'm inclined to believe this is an outside issue.

**Comment by twonirwana** [comment]
Thanks, i still looking into my internet connection but if anyone has the same problem a workaround seams to be to set the keepAlive of the HttpClient to false:

```
        DiscordClient discordClient = DiscordClientBuilder.create(token)
                .setReactorResources(ReactorResources.builder()
                        .httpClient(HttpClient.create()
                                .compress(true)
                                .keepAlive(false)
                                .followRedirect(true).secure())
                        .build()).build();
```

**Comment by laravieira** [comment]
I consistently get a connection reset after 5-6 minutes, even sending messages (but not receiving) every minute.
@twonirwana's snippet solves the issue. Here is an updated version (tested on 3.3.2), since `.create` doesn't have setters anymore:

```java
DiscordClient client = DiscordClient.builder(token)
    .setReactorResources(ReactorResources.builder()
        .httpClient(HttpClient.create()
            .compress(true)
            .keepAlive(false)
            .followRedirect(true)
            .secure())
        .build())
    .build()
```
