### ISSUE TITLE
NoSuchMethodError in DiscordWebClient.configureHttpClient when Trace logging enabled

### ISSUE THREAD

**Issue by gmt2001** [Discord4J/Discord4J#1071]
When trace logging is enabled, a NoSuchMethodError is thrown by the rest client observer while attempting to setup a gateway connection

https://github.com/Discord4J/Discord4J/blob/33f78ca76a6021bfe349af6e8dc61e0327c4973a/rest/src/main/java/discord4j/rest/http/client/DiscordWebClient.java#L82-L95

**To Reproduce:**
```java
reactor.util.Loggers.useVerboseConsoleLoggers();
DiscordClient client = DiscordClientBuilder.create(token).build();
client.gateway().login(DefaultGatewayClient::new).doOnSuccess(cgateway -> {
    System.out.println("Connected. My ID is " + cgateway.getSelfId().asString());
}).doOnError(e -> {
    e.printStackTrace();
}).subscribe();
```

**Expected Behavior:**
The HttpClient successfully performs the request, a gateway connection is eventually established, and the Connected message prints.

**Actual Behavior:**
The HttpClient throws an exception after the _configured_ stage and the pipeline terminates.

```
[TRACE] (main) Creating RequestStream with key a39dc574 for request: /gateway/bot -> /gateway/bot
[TRACE] (main) [B:a39dc574, R:19b93fa8] ClientRequest{method=GET, url='/gateway/bot', headers=DefaultHttpHeaders[], body=null, id=19b93fa8}
[TRACE] (main) [59b38691] Subscribed to limiter
[TRACE] (d4j-limiter-1) [59b38691] Acquired a token, 49 tokens remaining
[DEBUG] (d4j-limiter-1) Creating a new [http] client pool [PoolFactory{evictionInterval=PT0S, leasingStrategy=fifo, maxConnections=500, maxIdleTime=-1, maxLifeTime=-1, metricsEnabled=false, pendingAcquireMaxCount=-1, pendingAcquireTimeout=45000}] for [discord.com:443]
[DEBUG] (reactor-http-nio-7) [id: 0xac0018b8] Created a new pooled channel, now 1 active connections and 0 inactive connections
[DEBUG] (reactor-http-nio-7) [id: 0xac0018b8] SSL enabled using engine SSLEngineImpl and SNI discord.com:443
[DEBUG] (reactor-http-nio-7) [id: 0xac0018b8] Initialized pipeline DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.sslReader = reactor.netty.tcp.SslProvider$SslReadHandler), (BootstrapHandlers$BootstrapInitializerHandler#0 = reactor.netty.channel.BootstrapHandlers$BootstrapInitializerHandler), (PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer#0 = reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.left.decompressor = io.netty.handler.codec.http.HttpContentDecompressor), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
[DEBUG] (reactor-http-nio-7) [id: 0xac0018b8, L:/192.168.3.134:57967 - R:discord.com/162.159.136.232:443] Registering pool release on close event for channel
[DEBUG] (reactor-http-nio-7) [id: 0xac0018b8, L:/192.168.3.134:57967 - R:discord.com/162.159.136.232:443] Channel connected, now 1 active connections and 0 inactive connections
[DEBUG] (reactor-http-nio-7) [id: 0xac0018b8, L:/192.168.3.134:57967 - R:discord.com/162.159.136.232:443] onStateChange(PooledConnection{channel=[id: 0xac0018b8, L:/192.168.3.134:57967 - R:discord.com/162.159.136.232:443]}, [connected])
[TRACE] (reactor-http-nio-7) [B:a39dc574, R:19b93fa8] [connected] PooledConnection{channel=[id: 0xac0018b8, L:/192.168.3.134:57967 - R:discord.com/162.159.136.232:443]}
[DEBUG] (reactor-http-nio-7) [id: 0xac0018b8, L:/192.168.3.134:57967 - R:discord.com/162.159.136.232:443] onStateChange(GET{uri=/, connection=PooledConnection{channel=[id: 0xac0018b8, L:/192.168.3.134:57967 - R:discord.com/162.159.136.232:443]}}, [configured])
WARNING: An exception 'java.lang.NoSuchMethodError: 
reactor.netty.http.client.HttpClientRequest.currentContextView()Lreactor/util/context/ContextView;' [enable DEBUG 
level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following 
exception:
java.lang.NoSuchMethodError: 
reactor.netty.http.client.HttpClientRequest.currentContextView()Lreactor/util/context/ContextView;
	at discord4j.rest.http.client.DiscordWebClient.lambda$configureHttpClient$0(DiscordWebClient.java:90)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:537)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:563)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnection.onStateChange(PooledConnectionProvider.java:450)
	at reactor.netty.channel.ChannelOperationsHandler.channelActive(ChannelOperationsHandler.java:65)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelActive(CombinedChannelDupl
exHandler.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
	at io.netty.channel.CombinedChannelDuplexHandler.channelActive(CombinedChannelDuplexHandler.java:211)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
	at reactor.netty.tcp.SslProvider$SslReadHandler.userEventTriggered(SslProvider.java:769)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
	at io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1837)
	at io.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:950)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1408)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:623)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:586)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)

[TRACE] (d4j-parallel-1-2) [59b38691] Released a token, 50 tokens remaining
```

**Version:** 3.2.2

**Other:** The issue was not present in the 3.1.x line

**Comment by quanticc** [comment]
it's likely you have a transitive dependency pulling a different reactor-netty version where this method doesn't exist

D4J 3.2.x depends on reactor-netty 1.0.x where that method is present

Can you check whether another dep is pulling older reactor-netty?

**Comment by gmt2001** [comment]
My apologies. It appears Apache Ivy failed to fully evict since I was using the `reactor-netty` package while you were selecting only the individual sub-packages that were neccessary
