### ISSUE TITLE
Bot disconnects from voice channel after 10 seconds

### ISSUE THREAD

**Issue by vini2003** [Discord4J/Discord4J#1149]
**To Reproduce:**

Execute the following code with an appropriate token and type `!join` in a text channel, whilst connected to a voice channel.

```java
import discord4j.core.DiscordClientBuilder;
import discord4j.core.GatewayDiscordClient;
import discord4j.core.event.domain.message.MessageCreateEvent;
import discord4j.core.object.entity.Member;
import discord4j.core.object.entity.channel.VoiceChannel;
import discord4j.rest.util.Color;
import discord4j.voice.AudioProvider;

public class Bot {
    
    public static void main(String[] args) {
        
        // Create the Discord client
        final GatewayDiscordClient client = DiscordClientBuilder.create("TOKEN")
                                                                .build()
                                                                .login()
                                                                .block();
        
        // Event listener for messages
        client.getEventDispatcher().on(MessageCreateEvent.class)
              .subscribe(event -> {
            
                  // Extract the message content
                  String content = event.getMessage().getContent();
            
                  // Check if it's our "!join" command
                  if ("!join".equals(content)) {
                
                      // Get the member who sent the command
                      final Member member = event.getMember().orElse(null);
                
                      if (member != null) {
                    
                          // Get the voice state of the member, if exists
                          member.getVoiceState().blockOptional().ifPresent(voiceState -> {
                        
                              // Get the voice channel of the member, if exists
                              final VoiceChannel channel = voiceState.getChannel().block();
                        
                              if (channel != null) {
                            
                                  // Join the voice channel and provide an AudioProvider
                                  channel.join(spec -> spec.setProvider(AudioProvider.NO_OP)).block();
                              }
                          });
                      }
                  }
              });
        
        // Log in and start blocking, not letting the program end
        client.onDisconnect().block();
    }
}
```

**Expected Behavior:** 

The bot joins the channel and remains there.

**Actual Behavior:**

The bot joins the channel and leaves it after 10 seconds.

```
> Task :Bot.main()
[2023-05-10, 20:14:11.540, main] [d.c.DiscordClientBuilder,  INFO] Discord4J 3.2.3 (https://discord4j.com)
[2023-05-10, 20:14:13.786, reactor-http-nio-3] [d.g.DefaultGatewayClient,  INFO] [G:5adb727e, S:0] Connected to Gateway
[2023-05-10, 20:14:13.787, reactor-http-nio-3] [d.c.s.LocalShardCoordinator,  INFO] [G:5adb727e, S:0] Shard connected
[2023-05-10, 20:14:20.634, reactor-http-nio-4] [d.v.DefaultVoiceGatewayClient,  INFO] [G:5adb727e, S:0, guildId:878417486851223573] Identifying
[2023-05-10, 20:14:20.658, reactor-http-nio-4] [d.v.DefaultVoiceGatewayClient,  INFO] [G:5adb727e, S:0, guildId:878417486851223573] Waiting for session description
[2023-05-10, 20:14:30.138, d4j-events-1] [r.c.publisher.Operators, ERROR] Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'flatMap' (and no fallback has been configured)
Caused by: reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'flatMap' (and no fallback has been configured)
	at reactor.core.Exceptions.propagate(Exceptions.java:396)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1707)
	at ffs.Bot.lambda$main$1(Bot.java:45)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at ffs.Bot.lambda$main$2(Bot.java:37)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
Caused by: reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'flatMap' (and no fallback has been configured)

	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.tryOnNext(FluxHandleFuseable.java:132)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.tryOnNext(FluxMapFuseable.java:317)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.tryOnNext(FluxFilterFuseable.java:367)
	at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.runAsync(FluxPublishOn.java:992)
	at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.run(FluxPublishOn.java:1067)
	at reactor.scheduler.forkjoin.ForkJoinPoolScheduler$DisposableWorkerTask.run(ForkJoinPoolScheduler.java:443)
	at reactor.scheduler.forkjoin.ForkJoinPoolScheduler$Worker.processTaskQueue(ForkJoinPoolScheduler.java:407)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		... 20 common frames omitted
Caused by: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'flatMap' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
Caused by: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'flatMap' (and no fallback has been configured)

	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Version:**

3.2.4

**Comment by vini2003** [comment]
Increasing timeouts and retries does not solve the issue.

**Comment by quanticc** [comment]
Your log points to v Discord4J 3.2.3 , can you retry with 3.2.4? a change was applied to voice server handshake so voice only works with 3.2.4 or newer now.

**Comment by vini2003** [comment]
My bad! I updated my `gradle.properties` but as it turns out, the `build.gradle`'s version was hardcoded. And I managed to entire miss the log!

It works now. Thank you so much! ❤️
