### ISSUE TITLE
Response of newly created guild scheduled causes ValueInstantiationException

### ISSUE THREAD

**Issue by 125m125** [Discord4J/Discord4J#1155]
**To Reproduce:**
Create an external event:
```java
      Builder builder = ScheduledEventCreateSpec.builder();
      builder.name("___: _______");
      builder.scheduledStartTime(ZonedDateTime.now().plusHours(1).toInstant());
      builder.scheduledEndTime(ZonedDateTime.now().plusHours(2).toInstant());
      builder.privacyLevel(PrivacyLevel.GUILD_ONLY);
      builder.entityType(EntityType.EXTERNAL);
      builder.entityMetadata(ScheduledEventEntityMetadataSpec.builder().location("TBA").build());
      gatewayDiscordClient.getGuildById(Snowflake.of(935234113919660033L))
          .flatMap(x -> x.createScheduledEvent(builder.build())).subscribe(
              m -> log.debug("Created scheduled event for {} in guild {}", 1L, 935234113919660033L),
              e -> log.warn("Failed to create or update scheduled event:", e));
```

**Expected Behavior:** The Guild Scheduled Event is created and the response parsed successfully.

**Actual Behavior:** The Event is created successfully, but an Exception occurs when parsing the response:
```java
21:33:27.287 [reactor-http-nio-3] WARN  d.g.payload.JacksonPayloadReader:290 - Error while decoding JSON (com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `discord4j.discordjson.json.ImmutableGuildScheduledEventData`, problem: java.util.Optional cannot be cast to java.lang.String
 at [Source: UNKNOWN; line: -1, column: -1]): {"t":"GUILD_SCHEDULED_EVENT_CREATE","s":14,"op":0,"d":{"status":1,"sku_ids":[],"scheduled_start_time":"2023-06-18T21:00:00+00:00","scheduled_end_time":"2023-06-18T22:00:00+00:00","privacy_level":2,"name":"___: _______","image":null,"id":"1120073806816489582","guild_id":"935234113919660033","entity_type":3,"entity_metadata":{"location":"TBA"},"entity_id":null,"description":null,"creator_id":"1026096354201714799","channel_id":null}}
21:33:27.310 [boundedElastic-1] WARN  d._.i.d.u.i.UcCreateOrUpdateScheduledEventImpl:191 - Failed to create or update scheduled event:
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `discord4j.discordjson.json.ImmutableGuildScheduledEventData`, problem: java.util.Optional cannot be cast to java.lang.String
 at [Source: (byte[])"{"id": "1120073806816489582", "guild_id": "935234113919660033", "channel_id": null, "creator_id": "1026096354201714799", "name": "___: _______", "description": null, "image": null, "scheduled_start_time": "2023-06-18T21:00:00+00:00", "scheduled_end_time": "2023-06-18T22:00:00+00:00", "privacy_level": 2, "status": 1, "entity_type": 3, "entity_id": null, "entity_metadata": {"location": "TBA"}, "sku_ids": []}"; line: 1, column: 409]
	at discord4j.rest.http.JacksonReaderStrategy.lambda$read$0(JacksonReaderStrategy.java:74)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Body from POST /guilds/935234113919660033/scheduled-events [ClientResponse]
Stack trace:
		at discord4j.rest.http.JacksonReaderStrategy.lambda$read$0(JacksonReaderStrategy.java:74)
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
		at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:119)
		at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
		at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
		at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
		at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
		at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
		at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
		at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400)
		at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
		at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
		at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:684)
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
		at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
		at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:748)
```

**Version:** 3.2.5

**Other:**

**Comment by quanticc** [comment]
Thanks for the report, this is caused by `"description": null` which is not properly typed in [GuildScheduledEventData](https://github.com/Discord4J/discord-json/blob/1.6.x/src/main/java/discord4j/discordjson/json/GuildScheduledEventData.java#L38) according to [docs](https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event-object-guild-scheduled-event-structure)

A fix will be applied to that project. It seems we're also missing some fields
