### ISSUE TITLE
ApplicationInfoData fails to deserialize

### ISSUE THREAD

**Issue by kashike** [Discord4J/Discord4J#1243]
**To Reproduce:** 
```java
package com.example;

import discord4j.core.DiscordClientBuilder;
import discord4j.core.GatewayDiscordClient;
import discord4j.core.shard.ShardingStrategy;
import discord4j.rest.util.AllowedMentions;

public class What {
  public static void main(final String[] args) {
    final GatewayDiscordClient client = DiscordClientBuilder.create("redacted")
      .setDefaultAllowedMentions(AllowedMentions.suppressEveryone())
      .build()
      .gateway()
      .setSharding(ShardingStrategy.recommended())
      .login()
      .block();
    System.out.println(client.getRestClient().getApplicationId().blockOptional().orElseThrow());
  }
}
```

**Expected Behavior:** 
The application id should be output.

**Actual Behavior:** 
```
19:17:17.479 [main] INFO discord4j.core.DiscordClientBuilder -- Discord4J 3.3.0-RC1-73-g2e6f287 (https://discord4j.com)
19:17:19.435 [reactor-http-nio-3] INFO discord4j.gateway.DefaultGatewayClient -- [G:9487fed, S:0] Connected to Gateway
19:17:19.437 [reactor-http-nio-3] INFO discord4j.core.shard.LocalShardCoordinator -- [G:9487fed, S:0] Shard connected
Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `discord4j.discordjson.json.ImmutableApplicationInfoData`, problem: class java.util.Optional cannot be cast to class java.lang.String (java.util.Optional and java.lang.String are in module java.base of loader 'bootstrap')
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1449]
    at discord4j.rest.http.JacksonReaderStrategy.lambda$read$0(JacksonReaderStrategy.java:74)
    Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: 
Error has been observed at the following site(s):
    *__checkpoint ? Body from GET /oauth2/applications/@me [ClientResponse]
Original Stack Trace:
        at discord4j.rest.http.JacksonReaderStrategy.lambda$read$0(JacksonReaderStrategy.java:74)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
```

**Version:** 
`Discord4J 3.3.0-RC1-73-g2e6f287`

**Other:**

**Comment by Doc94** [comment]
Based in test this is caused because when call https://discord.com/developers/docs/topics/oauth2#get-current-bot-application-information return a object whith interactions_endpoint_url or role_connections_verification_url using null values like its not like say https://discord.com/developers/docs/resources/application#application-object-application-structure where is possible but not optional.

I create https://github.com/discord/discord-api-docs/issues/6999 for information about if this is expected now or is a error.

**Comment by Azn9** [comment]
I'm working on a patch; it should be fixed in a few hours

**Comment by Azn9** [comment]
Hello, once https://github.com/Discord4J/Discord4J/actions/runs/10011928453 completes, the new version with the fix will be available!
