### ISSUE TITLE
Impossible cast ForumChannel to the TopLevelGuildMessageChannel in ThreadChannel.getParent() if a thread is in a forum

### ISSUE THREAD

**Issue by nikolayKeniston** [Discord4J/Discord4J#1269]
If ThreadChannel is inside a forum, then the getParent() method tries to cast ForumChannel to TopLevelGuildMessageChannel, but ForumChannel does not inherit from it, and the result of the cast is always an exception.
The inheritors of TopLevelGuildMessageChannel are only NewsChannel, TextChannel and VoiceChannel; ThreadChannel in turn inherits from GuildMessageChannel, which is the parent interface for TopLevelGuildMessageChannel.
Code: https://github.com/Discord4J/Discord4J/blob/72a8b846ecbb9a24935bfe72bef051519e374968/core/src/main/java/discord4j/core/object/entity/channel/ThreadChannel.java#L88-L92

**To Reproduce:** thread.parent.block(), where thread is ThreadChannel

**Expected Behavior:** ForumChannel must inherit TopLevelGuildMessageChannel and not throw cast exceptions

**Actual Behavior:** Cast exception

**Version:** 3.3.0-RC1

**Other:** Stacktrace:
```
java.lang.ClassCastException: Cannot cast discord4j.core.object.entity.channel.ForumChannel to discord4j.core.object.entity.channel.TopLevelGuildMessageChannel
    at java.lang.Class.cast(Class.java:3369)
    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
    at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
    at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
    at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400)
    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
    at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2196)
    at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2070)
    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
    at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
    at reactor.core.publisher.Mono.subscribe(Mono.java:4490)
    at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203)
    at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
    at reactor.core.publisher.Mono.subscribe(Mono.java:4475)
```

**Comment by Azn9** [comment]
Thanks for the report! I'll fix this asap ;)
