### ISSUE TITLE
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

### ISSUE THREAD

**Issue by mandree95** [Discord4J/Discord4J#484]
**To Reproduce:**
Create the client
```java
ClientBuilder clientBuilder = new ClientBuilder();
clientBuilder.withToken(apiToken);
IDiscordClient client = clientBuilder.login();
client.getDispatcher().registerListener(myListener);
```
Inside the listener, just send back `test123` as response.
```java
@EventSubscriber
public void onMessageReceived(MessageReceivedEvent event) throws Exception {
    event.getChannel().sendMessage("test123");
}
```

**Expected Behavior:** Messages should be sent normally.

**Actual Behavior:** Sometimes messages can't be sent and the following stacktrace is printed in stdout.

**Version:** 2.10.1

**Other:** Application is running inside a docker container based on openjdk:11-slim

---

Stacktrace:
```
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
  at java.base/sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:526) ~[na:na]
  at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:464) ~[httpclient-4.5.6.jar!/:4.5.6]
  at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:397) ~[httpclient-4.5.6.jar!/:4.5.6]
  at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355) ~[httpclient-4.5.6.jar!/:4.5.6]
  at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.6.jar!/:4.5.6]
  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373) ~[httpclient-4.5.6.jar!/:4.5.6]
  at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394) ~[httpclient-4.5.6.jar!/:4.5.6]
  at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.6.jar!/:4.5.6]
  at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.6.jar!/:4.5.6]
  at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.6.jar!/:4.5.6]
  at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.6.jar!/:4.5.6]
  at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.6.jar!/:4.5.6]
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.6.jar!/:4.5.6]
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.6.jar!/:4.5.6]
  at sx.blah.discord.api.internal.Requests$Request.request(Requests.java:297) ~[Discord4J-2.10.1.jar!/:na]
  at sx.blah.discord.api.internal.Requests$Request.request(Requests.java:263) ~[Discord4J-2.10.1.jar!/:na]
  at sx.blah.discord.api.internal.Requests$Request.makeRequest(Requests.java:252) ~[Discord4J-2.10.1.jar!/:na]
  at sx.blah.discord.api.internal.Requests$Request.makeRequest(Requests.java:210) ~[Discord4J-2.10.1.jar!/:na]
  at sx.blah.discord.api.internal.Requests$Request.makeRequest(Requests.java:161) ~[Discord4J-2.10.1.jar!/:na]
  at sx.blah.discord.handle.impl.obj.Channel.sendMessage(Channel.java:468) ~[Discord4J-2.10.1.jar!/:na]
  at sx.blah.discord.handle.impl.obj.Channel.sendMessage(Channel.java:449) ~[Discord4J-2.10.1.jar!/:na]
  at sx.blah.discord.handle.impl.obj.Channel.sendMessage(Channel.java:439) ~[Discord4J-2.10.1.jar!/:na]
```

**Comment by GrandPanda** [comment]
This could be related to https://bugs.openjdk.java.net/browse/JDK-8209965.

**Comment by emre1702** [comment]
Got the same problem since I updated my project to JDK 11.
