### ISSUE TITLE
Unable to process JSON

### ISSUE THREAD

**Issue by Neytoro** [Discord4J/Discord4J#553]
**To Reproduce:** I wish I knew! I have multiple different bots that I've developed, all using Discord4J and running in multiple guilds. None of them, however, have this issue. What's more is the issue only occurs in one guild and I cannot isolate why.

**Expected Behavior:** The bot to oppropriately connect to the guild.

**Actual Behavior:** Throws an error and fails to load the guild. 2 out of 3 guilds load perfectly fine while the third generates this error: 

15:22:50.639: [ERROR][Dispatch Handler][sx.blah.discord.Discord4J] - Unable to process JSON!
java.lang.ArrayIndexOutOfBoundsException: 4
	at sx.blah.discord.api.internal.DiscordUtils.getPresenceFromJSON(DiscordUtils.java:685)
	at sx.blah.discord.api.internal.DiscordUtils.getPresenceFromJSON(DiscordUtils.java:660)
	at sx.blah.discord.api.internal.DiscordUtils.getGuildFromJSON(DiscordUtils.java:342)
	at sx.blah.discord.api.internal.DispatchHandler.guildCreate(DispatchHandler.java:347)
	at sx.blah.discord.api.internal.DispatchHandler.lambda$handle$0(DispatchHandler.java:130)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Version:** 3.0.1 - 3.0.8

**Other:** I apologize if I have overlooked an answer to this problem elsewhere, but I feel I have searched everywhere to no avail. I've tried multiple things, including: kicking and re-inviting to the broken guild, regenerating the bot token, and testing role permissions.

The guild shows the bot as being online, but the bot is unresponsive to any commands and appears to not see anything going on. I had this error in the past, but strangely it stopped occurring after a period of time. I suspected perhaps it was a Discord problem, but it is back once again and causing problems in the guild that relies on this bot. Any help or feedback is appreciated.

**Comment by danthonywalker** [comment]
This is not v3 as noted by the `sx.blah.discord`.
We do not support v2.
