### ISSUE TITLE
ClassCastException on ChannelDispatchHandler#channelPinsUpdate

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#691]
**To Reproduce:** Update channel pins.

**Expected Behavior:** No exception.

**Actual Behavior:** 
```
2020-05-02 15:33:37.878 ERROR [reactor-http-epoll-3/discord4j.core.shard.GatewayBootstrap]: [G:2d7857e6, S:9] Error dispatching event
java.lang.ClassCastException: class java.util.Optional cannot be cast to class java.lang.String (java.util.Optional and java.lang.String are in module java.base of loader 'bootstrap')
	at java.base/java.util.Optional.map(Optional.java:265)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Dispatch handled for class discord4j.discordjson.json.gateway.ImmutableChannelPinsUpdate
Stack trace:
		at java.base/java.util.Optional.map(Optional.java:265)
		at discord4j.core.event.dispatch.ChannelDispatchHandlers.channelPinsUpdate(ChannelDispatchHandlers.java:233)
		at discord4j.core.event.dispatch.DispatchHandlers.lambda$handle$1(DispatchHandlers.java:124)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4210)
```

**Version:** 3.1.0-SNAPSHOT

**Comment by quanticc** [comment]
We might have to change the type to a `Possible<Optional<String>>` because that error occurs if we deserialize `null` for a Possible field.

**Comment by Shadorc** [comment]
Related discord-api-docs issue: https://github.com/discord/discord-api-docs/pull/1588
