### ISSUE TITLE
Random periodic failures for `guild.getJoinTime()`

### ISSUE THREAD

**Issue by billsboard** [Discord4J/Discord4J#743]
**To Reproduce:** 
Run a bot with the `guild.getJoinTime()` function and wait a while (a few hours) and then call it. At seemingly random intervals, the method call will start producing errors.

**Expected Behavior:** 
Returns the proper date-time of the join time for the Bot

**Actual Behavior:** 
After a while, this error tends to show up for no apparent reason

java.time.format.DateTimeParseException: Text '' could not be parsed at index 0
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
        at discord4j.core.object.entity.Guild.getJoinTime(Guild.java:723)
        at ReaderThread.lambda$run$1(ReaderThread.java:34)
        at discord4j.core.spec.MessageCreateSpec.setEmbed(MessageCreateSpec.java:98)
        at discord4j.core.object.entity.channel.MessageChannel.lambda$createEmbed$1(MessageChannel.java:97)
        at discord4j.core.object.entity.channel.BaseMessageChannel.lambda$createMessage$3(BaseMessageChannel.java:81)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4210)
        at reactor.core.publisher.Mono.block(Mono.java:1665)
        at BotUtils.sendMessage(BotUtils.java:73)
        at ReaderThread.run(ReaderThread.java:37)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                at reactor.core.publisher.Mono.block(Mono.java:1666)
                ... 2 more
**Version:** 
3.1.0RC4

**Other:**

**Comment by quanticc** [comment]
Applied a temporary fix in ae115a7. Could you try with the [latest snapshot](https://github.com/Discord4J/Discord4J/wiki/Migrating-from-v3.0-to-v3.1#updating-dependencies)?

**Comment by billsboard** [comment]
Stops erroring, but it gets really slow overtime (ie bot takes long time to respond)? I notice this doesn't happen with M1 or RC2

**Comment by quanticc** [comment]
Hmm it seems unrelated to this issue. If a request takes a lot of time you could check if it's making API requests underneath, using `discord4j.rest` logger. https://github.com/Discord4J/Discord4J/wiki/Logging#v31-loggers

I'm going to close this ticket as the `DateTimeParseException` was fixed by above commit. Maybe the slowness deserves another GH issue with some example we could track overtime as well.
