### ISSUE TITLE
NPE when creating webhook on TextChannel without avatar image

### ISSUE THREAD

**Issue by AlexMl** [Discord4J/Discord4J#777]
Since I migrated my application to 3.1.X I found that I couldn't create webhooks without an avatar.

**To Reproduce:** 
This is the piece of code I use to create webhooks for one channel. It used to work just fine before the migration.
```
Webhook hook = gatewayClient.getChannelById(CHANNEL_ID)
                    .cast(TextChannel.class)
                    .flatMap(channel -> channel.createWebhook(spec -> {
                        spec.setName("chat-hook");
                        spec.setReason("Recreated chat hook!");
                    })).doOnError(errorSubscriber).blockOptional().orElse(null);
```
**Expected Behavior:**
Webhook with given spec created without error.

**Actual Behavior:**
Throws NPE with "avatar" as message
```
2020-09-16 18:42:54,734 WARN [epollEventLoopGroup-3-4] n.m.m.u.DiscordIntegrationUtil [DiscordIntegrationUtil.java:58] Caught discord error: avatar
java.lang.NullPointerException: avatar
        at java.util.Objects.requireNonNull(Objects.java:228) ~[na:1.8.0]
        at discord4j.discordjson.json.ImmutableWebhookCreateRequest$Builder.avatar(ImmutableWebhookCreateRequest.java:270)
        at discord4j.core.spec.WebhookCreateSpec.asRequest(WebhookCreateSpec.java:73)
        at discord4j.core.object.entity.channel.BaseGuildMessageChannel.lambda$createWebhook$3(BaseGuildMessageChannel.java:290)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2344)
        at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:155)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2152)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2026)
        at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:86)
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
        at reactor.core.publisher.Mono.blockOptional(Mono.java:1724)
        at my.app.alexml.DiscordIntegration.sendHookMessage(DiscordIntegration.java:601)
```

**Version:** 3.1.0 and 3.1.1 as well

**Other:**
From my investigations I can tell, that the image argument in the setAvatar() method is marked with the Nullable annotation in the WebhookCreateSpec.
Though in the WebhookCreateRequest Builder class it will throw an NPE with Objects.requireNonNull() when the avatar string is null.

**Comment by quanticc** [comment]
Thank you for the report. Patching this to have the fix available for `3.1.2-SNAPSHOT`
