### ISSUE TITLE
VoiceSocket error when connecting to voice channel

### ISSUE THREAD

**Issue by rjsuzuki** [Discord4J/Discord4J#849]
**To Reproduce:** 
I'm am still new to discord4j, but I think this is a bug:

1. Be logged into Discord and connect to a voice channel.
2. Start up discord bot and try to have it join the channel you already are present in.
3. Discord4j throws a 'No Such Method Error' when trying to access the VoiceSocket's getAddress() function.

Note: if I disconnect from the voice channel, then re-join a voice channel after Discord bot has joined the guild, it will join the voice channel successfully

**Expected Behavior:** 

Should not throw an error when joining voice channel.

**Actual Behavior:** 
```
15:24:37.288 [udp-nio-4] DEBUG i.n.c.AbstractChannelHandlerContext - An exception java.lang.NoSuchMethodError: reactor.netty.Connection.address()Ljava/net/InetSocketAddress;
	at discord4j.voice.VoiceSocket.lambda$null$0(VoiceSocket.java:66)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at reactor.netty.transport.ClientTransportConfig$ClientTransportDoOn.onStateChange(ClientTransportConfig.java:276)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:638)
	at reactor.netty.resources.NewConnectionProvider$NewConnectionObserver.onStateChange(NewConnectionProvider.java:190)
	at reactor.netty.channel.ChannelOperationsHandler.channelActive(ChannelOperationsHandler.java:63)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:249)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:253)
	at reactor.netty.transport.TransportConnector.lambda$doConnect$3(TransportConnector.java:150)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NoSuchMethodError: reactor.netty.Connection.address()Ljava/net/InetSocketAddress;
	at discord4j.voice.VoiceSocket.lambda$null$0(VoiceSocket.java:66)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at reactor.netty.transport.ClientTransportConfig$ClientTransportDoOn.onStateChange(ClientTransportConfig.java:276)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:638)
	at reactor.netty.resources.NewConnectionProvider$NewConnectionObserver.onStateChange(NewConnectionProvider.java:190)
	at reactor.netty.channel.ChannelOperationsHandler.channelActive(ChannelOperationsHandler.java:63)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:249)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:253)
	at reactor.netty.transport.TransportConnector.lambda$doConnect$3(TransportConnector.java:150)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Version:** 

v3.1.3 and v3.1.4-SNAPSHOT
lavaplayer v1.3.67

**Other:** <!-- Any other information you feel is relevant to the bug report. --
Spring boot v2.4.2 
kotlin v1.4.21

**Comment by quanticc** [comment]
Thanks for reporting this. It's actually a [change in reactor-netty](https://github.com/reactor/reactor-netty/commit/4346464a45c12b440ed8b6728653aba85293e7dd) that causes this because Connection#address no longer returns InetSocketAddress in your imported reactor-netty 1.0 from boot 2.4

I'm applying a fix to maintain compatibility with boot 2.4 / reactor-netty 1.0

Can you try with the latest 3.1.4-SNAPSHOT?

**Comment by rjsuzuki** [comment]
I'll give it a go my next opportunity! thanks

**Comment by rjsuzuki** [comment]
Looks good on initial tests for v3.1.4-SNAPSHOT. Errors are no longer present and behavior appears to be ok!
